#!/usr/bin/env python3
"""
Compare original and TRACER-refined GBM whole-cell profiles.

Runs in two stages so the TRACER-dependent work and the igraph-dependent work
live in different environments (see tutorials/gbm/README.md §4):

  --stage prep     builds whole-cell AnnData + purity/conflict metrics + QC.
                   Imports ``tracer`` -> run inside the Apptainer container.
                   Writes adata_orig_prepped.h5ad, adata_ft_prepped.h5ad and
                   prep_manifest.json.

  --stage cluster  reads the prepped h5ads and runs the scanpy pipeline
                   (normalize -> PCA -> neighbors -> UMAP -> Leiden -> markers).
                   Needs igraph/leidenalg -> run in the insitucnv_env conda env.
                   Writes profile_summary.csv, {original,finetuned}_top_markers.csv,
                   {original,finetuned}_marker_matrixplot.png, adata_orig.h5ad,
                   adata_ft.h5ad.

The scanpy helpers below import scanpy/matplotlib *inside* the functions and
touch no ``tracer`` at module load, so the cluster stage (and compare_three_way.py)
can import them in an environment without torch/open3d/tracer.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path
import sys


# TRACER writes the refined whole-cell label to cell_id_tracer (current) or
# cell_id_finetuned (runs before mid-2026). Prefer the current name; fall back.
TRACER_COL_CANDIDATES = ("cell_id_tracer", "cell_id_finetuned")
EXCLUDE_IDS = {"-1", "DROP", "nan"}


def _log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def _resolve_tracer_col(parquet_path) -> str:
    """Return whichever of TRACER_COL_CANDIDATES is present in the parquet schema.

    Reads only the schema (no data). Raises if neither candidate is found.
    """
    import pyarrow.parquet as pq  # kept local so importing this module stays light

    names = set(pq.read_schema(str(parquet_path)).names)
    for cand in TRACER_COL_CANDIDATES:
        if cand in names:
            return cand
    raise ValueError(
        f"None of the TRACER whole-cell columns {TRACER_COL_CANDIDATES} found in "
        f"{parquet_path} (schema has: {sorted(names)})"
    )


def _whole_cell_mask(labels):
    """Transcripts to EXCLUDE when building a TRACER whole-cell AnnData:
    unassigned-class labels and partial (multi-'-') component pseudo-ids."""
    s = labels.astype(str)
    return (
        s.isin(EXCLUDE_IDS)
        | s.str.startswith("UNASSIGNED")
        | (s.str.count("-") > 1)
    )


def _load_annotation_map(annotations_csv):
    """Patient4 cell_id -> annotation map. Strips the -P<n> patient suffix so
    keys match the parquet cell IDs."""
    import pandas as pd

    anno = pd.read_csv(annotations_csv, usecols=["cell_id", "annotation"])
    anno = anno[anno["cell_id"].str.endswith("-P4")].copy()
    anno["cell_id"] = anno["cell_id"].str.replace(r"-P\d+$", "", regex=True)
    return anno.set_index("cell_id")["annotation"]


def _attach_annotations(adata, anno_map) -> None:
    import pandas as pd

    if anno_map is None:
        return
    adata.obs["cell_type"] = pd.Index(adata.obs_names).map(anno_map).values


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare original and TRACER-refined GBM profiles.")
    parser.add_argument("--stage", required=True, choices=["prep", "cluster"],
                        help="prep = build AnnData + metrics (container); cluster = scanpy pipeline (conda env).")
    parser.add_argument("--outdir", required=True, help="Directory for prepped h5ads and final outputs.")
    # prep-only inputs (validated in _run_prep)
    parser.add_argument("--input", default=None, help="[prep] Merged TRACER parquet (cell_id + cell_id_tracer/finetuned).")
    parser.add_argument("--npmi", default=None, help="[prep] NPMI CSV generated by generate_npmi.py.")
    parser.add_argument("--annotations-csv", default=None,
                        help="[prep] adata_obs_annotated.csv with 'cell_id' and 'annotation' columns.")
    parser.add_argument("--min-transcripts", type=int, default=20, help="[prep] Minimum transcripts per cell for QC.")
    parser.add_argument("--min-genes", type=int, default=20, help="[prep] Minimum genes per cell for QC.")
    # cluster-only params
    parser.add_argument("--n-neighbors", type=int, default=15, help="[cluster] Scanpy neighbors parameter.")
    parser.add_argument("--leiden-resolution", type=float, default=1.0, help="[cluster] Leiden resolution.")
    parser.add_argument("--top-markers", type=int, default=10, help="[cluster] Top markers to save per cluster.")
    parser.add_argument("--matrixplot-genes", type=int, default=5, help="[cluster] Genes per cluster in matrixplots.")
    return parser.parse_args()


def _filter_qc(adata, *, min_transcripts: int, min_genes: int):
    mask = (adata.obs["n_transcripts"] >= min_transcripts) & (adata.obs["n_genes"] >= min_genes)
    return adata[mask].copy()


def _run_scanpy_pipeline(adata, *, prefix: str, n_neighbors: int, leiden_resolution: float):
    import scanpy as sc

    if adata.n_obs < 2 or adata.n_vars < 2:
        raise ValueError(f"{prefix}: not enough cells or genes after QC for Scanpy analysis.")

    _log(f"  [{prefix}] normalize_total ...")
    adata.layers["counts"] = adata.X.copy()
    sc.pp.normalize_total(adata, inplace=True)
    sc.pp.log1p(adata)

    n_pcs = min(30, adata.n_vars - 1, adata.n_obs - 1)
    if n_pcs < 2:
        raise ValueError(f"{prefix}: PCA requires at least two components after QC.")

    _log(f"  [{prefix}] PCA (n_comps={n_pcs}) ...")
    sc.pp.pca(adata, n_comps=n_pcs)

    n_neighbors_actual = min(n_neighbors, max(2, adata.n_obs - 1))
    _log(f"  [{prefix}] neighbors (k={n_neighbors_actual}) ...")
    sc.pp.neighbors(adata, n_neighbors=n_neighbors_actual, n_pcs=min(n_pcs, adata.obsm["X_pca"].shape[1]))

    _log(f"  [{prefix}] UMAP ...")
    sc.tl.umap(adata)

    leiden_key = f"{prefix}_leiden"
    _log(f"  [{prefix}] Leiden (resolution={leiden_resolution}) ...")
    sc.tl.leiden(adata, resolution=leiden_resolution, key_added=leiden_key)
    n_clusters = adata.obs[leiden_key].nunique()
    _log(f"  [{prefix}] {n_clusters} clusters found")
    if n_clusters < 2:
        raise ValueError(f"{prefix}: Leiden returned fewer than two clusters; cannot rank markers.")

    _log(f"  [{prefix}] rank_genes_groups (Wilcoxon) ...")
    sc.tl.rank_genes_groups(adata, groupby=leiden_key, method="wilcoxon")
    adata.uns["leiden_key"] = leiden_key
    return adata


def _extract_top_markers(adata, *, n_top: int):
    import scanpy as sc

    markers = sc.get.rank_genes_groups_df(adata, group=None)
    markers = markers.sort_values(["group", "scores"], ascending=[True, False]).copy()
    return markers.groupby("group", as_index=False, sort=False).head(n_top).reset_index(drop=True)


def _save_matrixplot(adata, output_path: Path, *, n_genes: int) -> None:
    import matplotlib.pyplot as plt
    import scanpy as sc

    sc.pl.rank_genes_groups_matrixplot(
        adata,
        n_genes=n_genes,
        values_to_plot="logfoldchanges",
        cmap="bwr",
        vmin=-2,
        vmax=2,
        min_logfoldchange=1.0,
        colorbar_title="log fold change",
        show=False,
    )
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close("all")


def _summary_row(name: str, adata) -> dict:
    leiden_key = adata.uns["leiden_key"]
    return {
        "dataset": name,
        "n_cells": int(adata.n_obs),
        "n_genes": int(adata.n_vars),
        "mean_transcripts": float(adata.obs["n_transcripts"].mean()),
        "mean_genes": float(adata.obs["n_genes"].mean()),
        "mean_purity": float(adata.obs["cell_purity"].dropna().mean()),
        "mean_conflict": float(adata.obs["conflict_score"].dropna().mean()),
        "n_clusters": int(adata.obs[leiden_key].nunique()),
    }


def _run_prep(args) -> None:
    """Stage A (container): build AnnData + purity/conflict + QC, write prepped h5ads."""
    import pandas as pd

    if not args.input or not args.npmi:
        raise SystemExit("--stage prep requires --input and --npmi.")

    input_path = Path(args.input)
    npmi_path = Path(args.npmi)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    tracer_col = _resolve_tracer_col(input_path)
    _log(f"TRACER whole-cell column: '{tracer_col}'")

    required = ["feature_name", "cell_id", tracer_col]
    _log(f"Reading parquet (columns: {required}) from {input_path} ...")
    df = pd.read_parquet(input_path, columns=required)
    _log(f"Loaded {len(df):,} rows  (mem: {df.memory_usage(deep=True).sum() / 1e9:.2f} GB)")

    _log("Casting column dtypes to str ...")
    df["feature_name"] = df["feature_name"].astype(str).str.strip()
    df["cell_id"] = df["cell_id"].astype(str)
    df[tracer_col] = df[tracer_col].astype(str)

    repo_root = Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(repo_root / "src"))

    from tracer.metrics import compute_purity_and_conflict
    from tracer.plot import make_adata

    _log(f"Reading NPMI from {npmi_path} ...")
    npmi_df = pd.read_csv(npmi_path)
    _log(f"NPMI table: {len(npmi_df):,} rows")

    _log("Building AnnData for original whole cells ...")
    adata_orig = make_adata(
        df,
        cell_col="cell_id",
        gene_col="feature_name",
        name="Original whole cells",
        exclude_ids=EXCLUDE_IDS,
    )
    _log(f"adata_orig: {adata_orig.n_obs:,} cells x {adata_orig.n_vars:,} genes")

    _log("Filtering to TRACER whole cells ...")
    df_ft_whole = df[~_whole_cell_mask(df[tracer_col])].copy()
    _log(f"TRACER whole-cell transcripts: {len(df_ft_whole):,}")

    _log("Building AnnData for TRACER whole cells ...")
    adata_ft = make_adata(
        df_ft_whole,
        cell_col=tracer_col,
        gene_col="feature_name",
        name="TRACER whole cells",
        exclude_ids=EXCLUDE_IDS,
    )
    _log(f"adata_ft: {adata_ft.n_obs:,} cells x {adata_ft.n_vars:,} genes")

    anno_map = None
    if args.annotations_csv:
        _log(f"Reading cell type annotations from {args.annotations_csv} ...")
        anno_map = _load_annotation_map(args.annotations_csv)
        _log(f"  annotation map: {len(anno_map):,} Patient4 cells")
        _attach_annotations(adata_orig, anno_map)
        _attach_annotations(adata_ft, anno_map)
        _log(f"  orig annotated: {adata_orig.obs['cell_type'].notna().sum():,} / {adata_orig.n_obs:,}")
        _log(f"  ft   annotated: {adata_ft.obs['cell_type'].notna().sum():,}  / {adata_ft.n_obs:,}")

    _log("Computing purity/conflict for original cells ...")
    compute_purity_and_conflict(
        filtered_df=df,
        nucleus_npmi_long=npmi_df,
        adata=adata_orig,
        cell_col="cell_id",
        min_transcripts_per_cell=3,
        npmi_threshold=0.05,
        purity_percentile=80.0,
        conflict_percentile=80.0,
        exclude_ids=EXCLUDE_IDS,
    )
    _log("Computing purity/conflict for TRACER cells ...")
    compute_purity_and_conflict(
        filtered_df=df_ft_whole,
        nucleus_npmi_long=npmi_df,
        adata=adata_ft,
        cell_col=tracer_col,
        min_transcripts_per_cell=3,
        npmi_threshold=0.05,
        purity_percentile=80.0,
        conflict_percentile=80.0,
        exclude_ids=EXCLUDE_IDS,
    )

    _log(f"QC filter: min_transcripts={args.min_transcripts}, min_genes={args.min_genes} ...")
    adata_orig = _filter_qc(adata_orig, min_transcripts=args.min_transcripts, min_genes=args.min_genes)
    adata_ft = _filter_qc(adata_ft, min_transcripts=args.min_transcripts, min_genes=args.min_genes)
    _log(f"After QC — original: {adata_orig.n_obs:,} cells  |  TRACER: {adata_ft.n_obs:,} cells")

    _log("Writing prepped h5ads ...")
    adata_orig.write_h5ad(outdir / "adata_orig_prepped.h5ad")
    adata_ft.write_h5ad(outdir / "adata_ft_prepped.h5ad")

    entries = [
        {"key": "original", "prefix": "original", "prepped": "adata_orig_prepped.h5ad",
         "final": "adata_orig.h5ad", "markers": "original_top_markers.csv",
         "matrixplot": "original_marker_matrixplot.png"},
        {"key": "finetuned", "prefix": "finetuned", "prepped": "adata_ft_prepped.h5ad",
         "final": "adata_ft.h5ad", "markers": "finetuned_top_markers.csv",
         "matrixplot": "finetuned_marker_matrixplot.png"},
    ]
    manifest = {
        "comparison": "two_way",
        "tracer_col": tracer_col,
        "params": {"min_transcripts": args.min_transcripts, "min_genes": args.min_genes},
        "entries": entries,
    }
    (outdir / "prep_manifest.json").write_text(json.dumps(manifest, indent=2))
    _log(f"Wrote prep_manifest.json + {len(entries)} prepped h5ads to {outdir}")


def _run_cluster(args) -> None:
    """Stage B (conda env): read prepped h5ads, run scanpy pipeline, write outputs."""
    import anndata as ad
    import pandas as pd

    outdir = Path(args.outdir)
    manifest_path = outdir / "prep_manifest.json"
    if not manifest_path.exists():
        raise SystemExit(f"Missing prep_manifest.json in {outdir}; run --stage prep first.")
    manifest = json.loads(manifest_path.read_text())
    entries = manifest["entries"]

    summary_rows = []
    for e in entries:
        prepped = outdir / e["prepped"]
        if not prepped.exists():
            raise SystemExit(f"Missing prepped h5ad: {prepped}; re-run --stage prep.")
        _log(f"[{e['key']}] reading prepped {prepped.name} ...")
        adata = ad.read_h5ad(prepped)
        _log(f"[{e['key']}] {adata.n_obs:,} cells x {adata.n_vars:,} genes")

        adata = _run_scanpy_pipeline(
            adata, prefix=e["prefix"],
            n_neighbors=args.n_neighbors, leiden_resolution=args.leiden_resolution,
        )

        markers = _extract_top_markers(adata, n_top=args.top_markers)
        markers.to_csv(outdir / e["markers"], index=False)
        _log(f"[{e['key']}] saving matrixplot ...")
        _save_matrixplot(adata, outdir / e["matrixplot"], n_genes=args.matrixplot_genes)

        summary_rows.append(_summary_row(e["key"], adata))

        adata.obs.drop(columns=["cell_purity_bool", "is_conflict"], errors="ignore", inplace=True)
        _log(f"[{e['key']}] saving {e['final']} ...")
        adata.write_h5ad(outdir / e["final"])

    pd.DataFrame(summary_rows).to_csv(outdir / "profile_summary.csv", index=False)
    _log(f"Done. Saved comparison outputs to: {outdir}")


def main() -> None:
    args = _parse_args()
    if args.stage == "prep":
        _run_prep(args)
    else:
        _run_cluster(args)


if __name__ == "__main__":
    main()
