#!/usr/bin/env python3
"""
Three-way comparison of GBM whole-cell profiles over the SAME tissue pieces:

  1. original   - pre-TRACER Xenium segmentation      (``cell_id``, new merged)
  2. tracer_may - previous TRACER run                 (``cell_id_finetuned``, old merged)
  3. tracer_new - current TRACER run                  (``cell_id_tracer``, new merged)

This generalizes ``compare_profiles.py`` (which compares original vs one TRACER
run in a single parquet) to three labelings across two merged parquets. The two
runs are aligned by ``piece_id`` (no transcript-level join): whichever pieces are
present in the NEW merged define the common set, and the OLD merged is restricted
to those pieces so the comparison is apples-to-apples regardless of whether the
new run has 7 or 8 pieces.

Runs in two stages (see tutorials/gbm/README.md §4), exactly like
compare_profiles.py:

  --stage prep     build whole-cell AnnData + purity/conflict + QC for all three
                   labelings. Imports ``tracer`` -> run in the Apptainer container.
                   Writes adata_<key>_prepped.h5ad + prep_manifest.json.
  --stage cluster  scanpy pipeline (normalize -> PCA -> neighbors -> UMAP ->
                   Leiden -> markers) on the prepped h5ads. Needs igraph/leidenalg
                   -> run in the insitucnv_env conda env. The cluster stage is the
                   shared compare_profiles._run_cluster (same prep_manifest.json).

EXAMPLE
=======
::

    # Stage A (container):
    python tutorials/gbm/compare_three_way.py --stage prep \\
      --new-merged tutorials/gbm/output/slide3_tracer_merged.parquet \\
      --old-merged tutorials/gbm/output/slide3_tracer_merged_2025-05-07.parquet \\
      --npmi       tutorials/gbm/data/gbm_npmi_no_controls.csv \\
      --outdir     tutorials/gbm/output/slide3_profile_comparison \\
      --annotations-csv /path/to/adata_obs_annotated.csv

    # Stage B (conda env insitucnv_env):
    python tutorials/gbm/compare_three_way.py --stage cluster \\
      --outdir tutorials/gbm/output/slide3_profile_comparison
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

# Reuse the two-way comparison helpers verbatim so the three labelings are scored
# and clustered identically to compare_profiles.py. Importing compare_profiles
# pulls in NO tracer (its tracer imports are inside functions), so this module is
# safe to import in the conda env for --stage cluster.
from compare_profiles import (
    EXCLUDE_IDS,
    _attach_annotations,
    _filter_qc,
    _load_annotation_map,
    _log,
    _resolve_tracer_col,
    _run_cluster,
    _sanitize_obs_for_h5ad,
    _whole_cell_mask,
)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Three-way comparison: original vs old vs new TRACER profiles."
    )
    parser.add_argument("--stage", required=True, choices=["prep", "cluster"],
                        help="prep = build AnnData + metrics (container); cluster = scanpy pipeline (conda env).")
    parser.add_argument("--outdir", required=True, help="Directory for prepped h5ads and final outputs.")
    # prep-only inputs
    parser.add_argument("--new-merged", default=None,
                        help="[prep] Merged parquet from the CURRENT TRACER run "
                             "(has cell_id + cell_id_tracer/cell_id_finetuned + piece_id).")
    parser.add_argument("--old-merged", default=None,
                        help="[prep] Merged parquet from the PREVIOUS TRACER run "
                             "(has cell_id_finetuned + piece_id).")
    parser.add_argument("--npmi", default=None, help="[prep] NPMI CSV generated by generate_npmi.py.")
    parser.add_argument("--annotations-csv", default=None,
                        help="[prep] adata_obs_annotated.csv with 'cell_id' and 'annotation' columns.")
    parser.add_argument("--min-transcripts", type=int, default=20, help="[prep] Minimum transcripts per cell for QC.")
    parser.add_argument("--min-genes", type=int, default=20, help="[prep] Minimum genes per cell for QC.")
    # cluster-only params (consumed by the shared compare_profiles._run_cluster)
    parser.add_argument("--n-neighbors", type=int, default=15, help="[cluster] Scanpy neighbors parameter.")
    parser.add_argument("--leiden-resolution", type=float, default=1.0, help="[cluster] Leiden resolution.")
    parser.add_argument("--top-markers", type=int, default=10, help="[cluster] Top markers to save per cluster.")
    parser.add_argument("--matrixplot-genes", type=int, default=5, help="[cluster] Genes per cluster in matrixplots.")
    return parser.parse_args()


def _run_prep(args) -> None:
    """Stage A (container): build the three labelings + metrics + QC, write prepped h5ads."""
    import pandas as pd

    if not args.new_merged or not args.old_merged or not args.npmi:
        raise SystemExit("--stage prep requires --new-merged, --old-merged and --npmi.")

    new_path = Path(args.new_merged)
    old_path = Path(args.old_merged)
    npmi_path = Path(args.npmi)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    repo_root = Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(repo_root / "src"))
    from tracer.metrics import compute_purity_and_conflict
    from tracer.plot import make_adata

    _log(f"Reading NPMI from {npmi_path} ...")
    npmi_df = pd.read_csv(npmi_path)
    _log(f"NPMI table: {len(npmi_df):,} rows")

    anno_map = None
    if args.annotations_csv:
        _log(f"Reading cell type annotations from {args.annotations_csv} ...")
        anno_map = _load_annotation_map(args.annotations_csv)
        _log(f"  annotation map: {len(anno_map):,} Patient4 cells")

    def _pc(df, adata, cell_col):
        compute_purity_and_conflict(
            filtered_df=df,
            nucleus_npmi_long=npmi_df,
            adata=adata,
            cell_col=cell_col,
            min_transcripts_per_cell=3,
            npmi_threshold=0.05,
            purity_percentile=80.0,
            conflict_percentile=80.0,
            exclude_ids=EXCLUDE_IDS,
        )

    adatas: dict[str, object] = {}

    # ---- NEW merged: original (cell_id) + tracer_new (cell_id_tracer) ----
    new_tracer_col = _resolve_tracer_col(new_path)
    _log(f"NEW merged TRACER column: '{new_tracer_col}'")
    new_cols = ["feature_name", "cell_id", new_tracer_col, "piece_id"]
    _log(f"Reading NEW merged (columns: {new_cols}) from {new_path} ...")
    new_df = pd.read_parquet(new_path, columns=new_cols)
    new_df["feature_name"] = new_df["feature_name"].astype(str).str.strip()
    new_df["cell_id"] = new_df["cell_id"].astype(str)
    new_df[new_tracer_col] = new_df[new_tracer_col].astype(str)

    common_pieces = sorted(new_df["piece_id"].astype(str).unique())
    _log(f"NEW merged: {len(new_df):,} rows across {len(common_pieces)} pieces: {common_pieces}")

    _log("Building AnnData: original whole cells (cell_id) ...")
    adata_original = make_adata(
        new_df, cell_col="cell_id", gene_col="feature_name",
        name="Original whole cells", exclude_ids=EXCLUDE_IDS,
    )
    _log(f"  adata_original: {adata_original.n_obs:,} cells x {adata_original.n_vars:,} genes")

    _log("Building AnnData: tracer_new whole cells ...")
    new_whole = new_df[~_whole_cell_mask(new_df[new_tracer_col])].copy()
    _log(f"  tracer_new whole-cell transcripts: {len(new_whole):,}")
    adata_new = make_adata(
        new_whole, cell_col=new_tracer_col, gene_col="feature_name",
        name="TRACER (new) whole cells", exclude_ids=EXCLUDE_IDS,
    )
    _log(f"  adata_tracer_new: {adata_new.n_obs:,} cells x {adata_new.n_vars:,} genes")

    _log("Computing purity/conflict: original ...")
    _pc(new_df, adata_original, "cell_id")
    _log("Computing purity/conflict: tracer_new ...")
    _pc(new_whole, adata_new, new_tracer_col)

    _attach_annotations(adata_original, anno_map)
    _attach_annotations(adata_new, anno_map)

    adatas["original"] = adata_original
    adatas["tracer_new"] = adata_new
    del new_df, new_whole

    # ---- OLD merged: tracer_may (cell_id_finetuned), restricted to common pieces ----
    old_tracer_col = _resolve_tracer_col(old_path)
    _log(f"OLD merged TRACER column: '{old_tracer_col}'")
    old_cols = ["feature_name", old_tracer_col, "piece_id"]
    _log(f"Reading OLD merged (columns: {old_cols}, pieces={common_pieces}) from {old_path} ...")
    old_df = pd.read_parquet(
        old_path, columns=old_cols,
        filters=[("piece_id", "in", common_pieces)],
    )
    old_df["feature_name"] = old_df["feature_name"].astype(str).str.strip()
    old_df[old_tracer_col] = old_df[old_tracer_col].astype(str)
    _log(f"OLD merged (restricted): {len(old_df):,} rows "
         f"across pieces {sorted(old_df['piece_id'].astype(str).unique())}")

    _log("Building AnnData: tracer_may whole cells ...")
    old_whole = old_df[~_whole_cell_mask(old_df[old_tracer_col])].copy()
    _log(f"  tracer_may whole-cell transcripts: {len(old_whole):,}")
    adata_may = make_adata(
        old_whole, cell_col=old_tracer_col, gene_col="feature_name",
        name="TRACER (May) whole cells", exclude_ids=EXCLUDE_IDS,
    )
    _log(f"  adata_tracer_may: {adata_may.n_obs:,} cells x {adata_may.n_vars:,} genes")

    _log("Computing purity/conflict: tracer_may ...")
    _pc(old_whole, adata_may, old_tracer_col)
    _attach_annotations(adata_may, anno_map)
    adatas["tracer_may"] = adata_may
    del old_df, old_whole

    # ---- QC filter + write prepped h5ads ----
    order = ["original", "tracer_may", "tracer_new"]
    entries = []
    for key in order:
        adata = _filter_qc(adatas[key], min_transcripts=args.min_transcripts, min_genes=args.min_genes)
        _log(f"[{key}] after QC: {adata.n_obs:,} cells")
        prepped = f"adata_{key}_prepped.h5ad"
        _sanitize_obs_for_h5ad(adata).write_h5ad(outdir / prepped)
        entries.append({
            "key": key, "prefix": key, "prepped": prepped,
            "final": f"adata_{key}.h5ad", "markers": f"{key}_top_markers.csv",
            "matrixplot": f"{key}_marker_matrixplot.png",
        })

    manifest = {
        "comparison": "three_way",
        "tracer_col_new": new_tracer_col,
        "tracer_col_old": old_tracer_col,
        "common_pieces": common_pieces,
        "params": {"min_transcripts": args.min_transcripts, "min_genes": args.min_genes},
        "entries": entries,
    }
    (outdir / "prep_manifest.json").write_text(json.dumps(manifest, indent=2))
    _log(f"Wrote prep_manifest.json + {len(entries)} prepped h5ads to {outdir}")


def main() -> None:
    args = _parse_args()
    if args.stage == "prep":
        _run_prep(args)
    else:
        # Cluster stage is identical to the two-way path (same prep_manifest.json).
        _run_cluster(args)


if __name__ == "__main__":
    main()
