#!/usr/bin/env python3
"""
Compare original and TRACER-refined GBM whole-cell profiles.
"""

from __future__ import annotations

import argparse
from datetime import datetime
from pathlib import Path
import sys


REQUIRED_COLUMNS = {"feature_name", "cell_id", "cell_id_finetuned"}
EXCLUDE_IDS = {"-1", "DROP", "nan"}


def _log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Compare original and TRACER-refined GBM profiles.")
    parser.add_argument("--input", required=True, help="Stage-5 TRACER parquet with cell_id_finetuned.")
    parser.add_argument("--npmi", required=True, help="NPMI CSV generated by generate_npmi.py.")
    parser.add_argument("--outdir", required=True, help="Directory for summary tables and plots.")
    parser.add_argument("--min-transcripts", type=int, default=20, help="Minimum transcripts per cell for QC.")
    parser.add_argument("--min-genes", type=int, default=20, help="Minimum genes per cell for QC.")
    parser.add_argument("--n-neighbors", type=int, default=15, help="Scanpy neighbors parameter.")
    parser.add_argument("--leiden-resolution", type=float, default=1.0, help="Leiden resolution.")
    parser.add_argument("--top-markers", type=int, default=10, help="Top markers to save per cluster.")
    parser.add_argument("--matrixplot-genes", type=int, default=5, help="Genes per cluster in matrixplots.")
    parser.add_argument("--annotations-csv", default=None,
                        help="adata_obs_annotated.csv with 'cell_id' and 'annotation' columns.")
    return parser.parse_args()


def _validate_columns(df: pd.DataFrame, required: set[str]) -> None:
    missing = sorted(required - set(df.columns))
    if missing:
        raise ValueError(f"Missing required columns: {', '.join(missing)}")


def _filter_qc(adata, *, min_transcripts: int, min_genes: int):
    mask = (adata.obs["n_transcripts"] >= min_transcripts) & (adata.obs["n_genes"] >= min_genes)
    return adata[mask].copy()


def _run_scanpy_pipeline(adata, *, prefix: str, n_neighbors: int, leiden_resolution: float):
    import scanpy as sc

    if adata.n_obs < 2 or adata.n_vars < 2:
        raise ValueError(f"{prefix}: not enough cells or genes after QC for Scanpy analysis.")

    _log(f"  [{prefix}] normalize_total ...")
    adata.layers["counts"] = adata.X.copy()
    sc.pp.normalize_total(adata, inplace=True)
    sc.pp.log1p(adata)

    n_pcs = min(30, adata.n_vars - 1, adata.n_obs - 1)
    if n_pcs < 2:
        raise ValueError(f"{prefix}: PCA requires at least two components after QC.")

    _log(f"  [{prefix}] PCA (n_comps={n_pcs}) ...")
    sc.pp.pca(adata, n_comps=n_pcs)

    n_neighbors_actual = min(n_neighbors, max(2, adata.n_obs - 1))
    _log(f"  [{prefix}] neighbors (k={n_neighbors_actual}) ...")
    sc.pp.neighbors(adata, n_neighbors=n_neighbors_actual, n_pcs=min(n_pcs, adata.obsm["X_pca"].shape[1]))

    _log(f"  [{prefix}] UMAP ...")
    sc.tl.umap(adata)

    leiden_key = f"{prefix}_leiden"
    _log(f"  [{prefix}] Leiden (resolution={leiden_resolution}) ...")
    sc.tl.leiden(adata, resolution=leiden_resolution, key_added=leiden_key)
    n_clusters = adata.obs[leiden_key].nunique()
    _log(f"  [{prefix}] {n_clusters} clusters found")
    if n_clusters < 2:
        raise ValueError(f"{prefix}: Leiden returned fewer than two clusters; cannot rank markers.")

    _log(f"  [{prefix}] rank_genes_groups (Wilcoxon) ...")
    sc.tl.rank_genes_groups(adata, groupby=leiden_key, method="wilcoxon")
    adata.uns["leiden_key"] = leiden_key
    return adata


def _extract_top_markers(adata, *, n_top: int) -> pd.DataFrame:
    import scanpy as sc

    markers = sc.get.rank_genes_groups_df(adata, group=None)
    markers = markers.sort_values(["group", "scores"], ascending=[True, False]).copy()
    return markers.groupby("group", as_index=False, sort=False).head(n_top).reset_index(drop=True)


def _save_matrixplot(adata, output_path: Path, *, n_genes: int) -> None:
    import matplotlib.pyplot as plt
    import scanpy as sc

    sc.pl.rank_genes_groups_matrixplot(
        adata,
        n_genes=n_genes,
        values_to_plot="logfoldchanges",
        cmap="bwr",
        vmin=-2,
        vmax=2,
        min_logfoldchange=1.0,
        colorbar_title="log fold change",
        show=False,
    )
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close("all")


def _summary_row(name: str, adata) -> dict[str, float | int | str]:
    leiden_key = adata.uns["leiden_key"]
    return {
        "dataset": name,
        "n_cells": int(adata.n_obs),
        "n_genes": int(adata.n_vars),
        "mean_transcripts": float(adata.obs["n_transcripts"].mean()),
        "mean_genes": float(adata.obs["n_genes"].mean()),
        "mean_purity": float(adata.obs["cell_purity"].dropna().mean()),
        "mean_conflict": float(adata.obs["conflict_score"].dropna().mean()),
        "n_clusters": int(adata.obs[leiden_key].nunique()),
    }


def main() -> None:
    args = _parse_args()

    import pandas as pd

    input_path = Path(args.input)
    npmi_path = Path(args.npmi)
    outdir = Path(args.outdir)
    outdir.mkdir(parents=True, exist_ok=True)

    _log(f"Reading parquet (columns: {sorted(REQUIRED_COLUMNS)}) from {input_path} ...")
    df = pd.read_parquet(input_path, columns=list(REQUIRED_COLUMNS))
    _log(f"Loaded {len(df):,} rows, {df.shape[1]} columns  "
         f"(mem: {df.memory_usage(deep=True).sum() / 1e9:.2f} GB)")

    _validate_columns(df, REQUIRED_COLUMNS)
    _log("Casting column dtypes to str ...")
    df["feature_name"] = df["feature_name"].astype(str).str.strip()
    df["cell_id"] = df["cell_id"].astype(str)
    df["cell_id_finetuned"] = df["cell_id_finetuned"].astype(str)
    _log(f"After cast  (mem: {df.memory_usage(deep=True).sum() / 1e9:.2f} GB)")

    repo_root = Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(repo_root / "src"))

    from tracer.metrics import compute_purity_and_conflict
    from tracer.plot import make_adata

    _log(f"Reading NPMI from {npmi_path} ...")
    npmi_df = pd.read_csv(npmi_path)
    _log(f"NPMI table: {len(npmi_df):,} rows")

    _log("Building AnnData for original whole cells ...")
    adata_orig = make_adata(
        df,
        cell_col="cell_id",
        gene_col="feature_name",
        name="Original whole cells",
        exclude_ids=EXCLUDE_IDS,
    )
    _log(f"adata_orig: {adata_orig.n_obs:,} cells × {adata_orig.n_vars:,} genes")

    _log("Filtering to TRACER finetuned whole cells ...")
    finetuned = df["cell_id_finetuned"].astype(str)
    exclude_mask = (
        finetuned.isin(EXCLUDE_IDS)
        | finetuned.str.startswith("UNASSIGNED")
        | (finetuned.str.count("-") > 1)
    )
    df_ft_whole = df[~exclude_mask].copy()
    _log(f"Finetuned whole-cell transcripts: {len(df_ft_whole):,}")

    _log("Building AnnData for TRACER finetuned whole cells ...")
    adata_ft = make_adata(
        df_ft_whole,
        cell_col="cell_id_finetuned",
        gene_col="feature_name",
        name="TRACER finetuned whole cells",
        exclude_ids=EXCLUDE_IDS,
    )
    _log(f"adata_ft: {adata_ft.n_obs:,} cells × {adata_ft.n_vars:,} genes")

    if args.annotations_csv:
        _log(f"Reading cell type annotations from {args.annotations_csv} ...")
        anno = pd.read_csv(args.annotations_csv, usecols=["cell_id", "annotation"])
        # Keep only Patient4 entries, then strip the "-P4" suffix to match parquet cell IDs.
        anno = anno[anno["cell_id"].str.endswith("-P4")].copy()
        anno["cell_id"] = anno["cell_id"].str.replace(r"-P\d+$", "", regex=True)
        anno_map = anno.set_index("cell_id")["annotation"]
        adata_orig.obs["cell_type"] = pd.Index(adata_orig.obs_names).map(anno_map).values
        adata_ft.obs["cell_type"] = pd.Index(adata_ft.obs_names).map(anno_map).values
        _log(f"  orig annotated: {adata_orig.obs['cell_type'].notna().sum():,} / {adata_orig.n_obs:,}")
        _log(f"  ft   annotated: {adata_ft.obs['cell_type'].notna().sum():,}  / {adata_ft.n_obs:,}")

    _log("Computing purity/conflict for original cells ...")
    compute_purity_and_conflict(
        filtered_df=df,
        nucleus_npmi_long=npmi_df,
        adata=adata_orig,
        cell_col="cell_id",
        min_transcripts_per_cell=3,
        npmi_threshold=0.05,
        purity_percentile=80.0,
        conflict_percentile=80.0,
        exclude_ids=EXCLUDE_IDS,
    )
    _log("Computing purity/conflict for finetuned cells ...")
    compute_purity_and_conflict(
        filtered_df=df_ft_whole,
        nucleus_npmi_long=npmi_df,
        adata=adata_ft,
        cell_col="cell_id_finetuned",
        min_transcripts_per_cell=3,
        npmi_threshold=0.05,
        purity_percentile=80.0,
        conflict_percentile=80.0,
        exclude_ids=EXCLUDE_IDS,
    )

    _log(f"QC filter: min_transcripts={args.min_transcripts}, min_genes={args.min_genes} ...")
    adata_orig = _filter_qc(adata_orig, min_transcripts=args.min_transcripts, min_genes=args.min_genes)
    adata_ft = _filter_qc(adata_ft, min_transcripts=args.min_transcripts, min_genes=args.min_genes)
    _log(f"After QC — original: {adata_orig.n_obs:,} cells  |  finetuned: {adata_ft.n_obs:,} cells")

    _log("Running Scanpy pipeline for original cells ...")
    adata_orig = _run_scanpy_pipeline(
        adata_orig,
        prefix="original",
        n_neighbors=args.n_neighbors,
        leiden_resolution=args.leiden_resolution,
    )

    _log("Running Scanpy pipeline for finetuned cells ...")
    adata_ft = _run_scanpy_pipeline(
        adata_ft,
        prefix="finetuned",
        n_neighbors=args.n_neighbors,
        leiden_resolution=args.leiden_resolution,
    )

    _log("Extracting top markers ...")
    orig_markers = _extract_top_markers(adata_orig, n_top=args.top_markers)
    ft_markers = _extract_top_markers(adata_ft, n_top=args.top_markers)

    _log(f"Writing outputs to {outdir} ...")
    summary = pd.DataFrame(
        [
            _summary_row("original", adata_orig),
            _summary_row("finetuned", adata_ft),
        ]
    )
    summary.to_csv(outdir / "profile_summary.csv", index=False)
    orig_markers.to_csv(outdir / "original_top_markers.csv", index=False)
    ft_markers.to_csv(outdir / "finetuned_top_markers.csv", index=False)

    _log("Saving matrixplot for original cells ...")
    _save_matrixplot(adata_orig, outdir / "original_marker_matrixplot.png", n_genes=args.matrixplot_genes)

    _log("Saving matrixplot for finetuned cells ...")
    _save_matrixplot(adata_ft, outdir / "finetuned_marker_matrixplot.png", n_genes=args.matrixplot_genes)

    for adata in (adata_orig, adata_ft):
        adata.obs.drop(columns=["cell_purity_bool", "is_conflict"], errors="ignore", inplace=True)

    _log("Saving adata_orig.h5ad ...")
    adata_orig.write_h5ad(outdir / "adata_orig.h5ad")
    _log("Saving adata_ft.h5ad ...")
    adata_ft.write_h5ad(outdir / "adata_ft.h5ad")

    _log(f"Done. Saved comparison outputs to: {outdir}")


if __name__ == "__main__":
    main()
