#!/usr/bin/env python3
"""
Run the TRACER GBM tutorial pipeline using the lung cancer parameter set.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import time
import pandas as pd

REQUIRED_COLUMNS = {"x", "y", "feature_name", "cell_id"}
COMMON_COLUMN_ALIASES = {
    "x_location": "x",
    "y_location": "y",
    "z_location": "z",
}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run TRACER on a GBM transcript parquet.")
    parser.add_argument("--input", help="Transcript parquet path.")
    parser.add_argument("--npmi", help="NPMI CSV generated by generate_npmi.py.")
    parser.add_argument("--output", help="Output parquet path for the finetuned transcript table.")
    parser.add_argument("--seed", type=int, default=42, help="Reproducibility seed.")
    parser.add_argument(
        "--run-smoke-test",
        action="store_true",
        help="Run the built-in reproducibility smoke test and exit.",
    )
    return parser.parse_args()


def _validate_args(args: argparse.Namespace) -> None:
    if args.run_smoke_test:
        return
    missing = [flag for flag in ("input", "npmi", "output") if getattr(args, flag) is None]
    if missing:
        raise SystemExit(f"Missing required arguments: {', '.join('--' + name for name in missing)}")


def _normalize_common_columns(df: pd.DataFrame) -> tuple[pd.DataFrame, dict[str, str]]:
    rename_map = {
        src: dst
        for src, dst in COMMON_COLUMN_ALIASES.items()
        if src in df.columns and dst not in df.columns
    }
    if rename_map:
        df = df.rename(columns=rename_map)
    return df, rename_map


def _load_transcripts(path: Path) -> tuple[pd.DataFrame, dict[str, str]]:
    df = pd.read_parquet(path)
    df, rename_map = _normalize_common_columns(df)
    missing = sorted(REQUIRED_COLUMNS - set(df.columns))
    if missing:
        raise ValueError(
            "Missing required columns: "
            f"{', '.join(missing)}. "
            "Accepted coordinate names are either x/y/z or raw Xenium x_location/y_location/z_location."
        )

    df = df.copy()
    if "z" not in df.columns:
        df["z"] = 0.0
    if "transcript_id" not in df.columns:
        df["transcript_id"] = df.index.astype(str)

    df["feature_name"] = df["feature_name"].astype(str).str.strip()
    df["cell_id"] = df["cell_id"].astype(str)

    return df, rename_map


def main() -> None:
    args = _parse_args()
    _validate_args(args)

    import numpy as np
    import pandas as pd

    repo_root = Path(__file__).resolve().parents[2]
    sys.path.insert(0, str(repo_root / "src"))

    from tracer.core import reproducibility_smoke_test, set_reproducibility_seed

    if args.run_smoke_test:
        set_reproducibility_seed(args.seed)
        reproducibility_smoke_test(seed=args.seed)
        print("Smoke test passed")
        return

    input_path = Path(args.input)
    npmi_path = Path(args.npmi)
    output_path = Path(args.output)

    print(f"Reading transcripts from: {input_path}")
    df_transcripts, rename_map = _load_transcripts(input_path)
    if rename_map:
        print(f"Normalized columns: {rename_map}")

    print(f"Reading NPMI table from: {npmi_path}")
    df_npmi = pd.read_csv(npmi_path)

    from tracer import (
        annotate_unassigned_components_fast,
        apply_stitching_to_transcripts_memory_efficient,
        enforce_spatial_coherence_fast,
        prune_genes_by_npmi_greedy,
        prune_transcripts_fast,
    )
    import torch
    from scipy.spatial import cKDTree
    from torch_geometric.data import Data

    set_reproducibility_seed(args.seed)
    torch.manual_seed(args.seed)

    def build_graph_fast(
        df: pd.DataFrame,
        *,
        k: int = 10,
        dist_threshold: float = 1.5,
        coord_cols: tuple[str, str, str] = ("x", "y", "z"),
    ) -> Data:
        coords = df[list(coord_cols)].to_numpy(dtype=np.float32)
        n = coords.shape[0]

        if n == 0:
            edge_index = torch.empty((2, 0), dtype=torch.int64)
            data = Data(pos=torch.empty((0, 3), dtype=torch.float32), edge_index=edge_index)
            data.gene_name = np.array([], dtype=str)
            data.id = np.array([], dtype=str)
            return data

        tree = cKDTree(coords)
        distances, indices = tree.query(coords, k=min(k + 1, n))

        if indices.ndim == 1:
            indices = indices[:, None]
            distances = distances[:, None]

        mask = distances <= dist_threshold
        mask[:, 0] = False

        src = np.repeat(np.arange(n), mask.sum(axis=1))
        tgt = indices[mask]
        edge_array = np.vstack([src, tgt]).astype(np.int64) if len(src) else np.empty((2, 0), dtype=np.int64)
        edge_index = torch.from_numpy(edge_array)

        data = Data(pos=torch.from_numpy(coords), edge_index=edge_index)
        data.gene_name = df["feature_name"].to_numpy().astype(str)
        data.id = df["transcript_id"].to_numpy().astype(str)

        print(f"Constructed {edge_index.shape[1]:,} edges among {n:,} transcripts (k<={k}, d<={dist_threshold} um)")
        return data

    print("Stage 1: prune_transcripts_fast")
    t0 = time.time()
    df_pruned, aux = prune_transcripts_fast(
        df=df_transcripts,
        npmi_df=df_npmi,
        cell_id_col="cell_id",
        gene_col="feature_name",
        threshold=-0.05,
        unassigned_id="-1",
        n_jobs=-1,
        show_progress=True,
    )
    print(f"Stage 1 done: rows={len(df_pruned):,} took {time.time() - t0:.1f}s")

    print("Stage 2: annotate_unassigned_components_fast")
    t0 = time.time()
    df_final = annotate_unassigned_components_fast(
        df_pruned=df_pruned,
        aux=aux,
        build_graph_fn=build_graph_fast,
        prune_fn=prune_genes_by_npmi_greedy,
        coord_cols=("x", "y", "z"),
        k=8,
        dist_threshold=1.5,
        min_comp_size=25,
        npmi_threshold=-0.1,
        unassigned_final_col="cell_id_npmi_cons_p2",
        cell_id_col="cell_id",
        gene_col="feature_name",
        transcript_id_col="transcript_id",
        show_progress=True,
    )
    print(f"Stage 2 done: rows={len(df_final):,} took {time.time() - t0:.1f}s")

    print("Stage 3: apply_stitching_to_transcripts_memory_efficient")
    t0 = time.time()
    df_stitched, _ = apply_stitching_to_transcripts_memory_efficient(
        df_final=df_final,
        aux=aux,
        entity_col="cell_id_final",
        gene_col="feature_name",
        coord_cols=("x", "y", "z"),
        purity_threshold=0.05,
        penalize_simplicity=True,
        deltaC_min=0.01,
        dist_threshold=5.0,
        use_3d=True,
        out_col="cell_id_stitched",
        show_progress=True,
    )
    print(f"Stage 3 done: rows={len(df_stitched):,} took {time.time() - t0:.1f}s")

    print("Stage 4: enforce_spatial_coherence_fast")
    t0 = time.time()
    df_split = enforce_spatial_coherence_fast(
        df_stitched=df_stitched,
        build_graph_fn=build_graph_fast,
        entity_col="cell_id_stitched",
        coord_cols=("x", "y", "z"),
        k=5,
        dist_threshold=5.0,
        out_col="cell_id_spatial",
        show_progress=True,
    )
    print(f"Stage 4 done: rows={len(df_split):,} took {time.time() - t0:.1f}s")

    print("Stage 5: apply_stitching_to_transcripts_memory_efficient")
    t0 = time.time()
    df_finetuned, _ = apply_stitching_to_transcripts_memory_efficient(
        df_final=df_split,
        aux=aux,
        entity_col="cell_id_spatial",
        gene_col="feature_name",
        coord_cols=("x", "y", "z"),
        purity_threshold=0.05,
        penalize_simplicity=True,
        deltaC_min=0.01,
        dist_threshold=5.0,
        use_3d=True,
        out_col="cell_id_finetuned",
        show_progress=True,
    )
    print(f"Stage 5 done: rows={len(df_finetuned):,} took {time.time() - t0:.1f}s")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    df_finetuned.to_parquet(output_path, index=False)
    print(f"Saved finetuned output to: {output_path}")


if __name__ == "__main__":
    main()
