#!/usr/bin/env python3
"""Run the TRACER GBM pipeline through the *canonical* tested entry point.

History / why this file changed
-------------------------------
The previous version of this script hand-rolled the whole TRACER workflow:
it copied ~900 lines of private helpers "verbatim from
tests/_pipeline_runner.py" and re-implemented the Prune → Rescue → Group →
Stitch → Demote → Final-Rescue orchestration inline. That fork drifted from
the tested pipeline (`tracer.pipeline.run_segmented_pipeline`, which is what
`scripts/run_tracer.py` and `tests/_pipeline_runner.py` exercise) and used
stale rescue defaults (legacy ``rank_policy="distance"`` instead of the
config's ``"witness"`` cap), which on large full-tissue GBM samples led to
runaway Stitch/rescue work and effectively non-terminating runtimes.

This version does ONE thing: load the GBM inputs and call the same tested
pipeline path as ``run_tracer.py``. No algorithm logic lives here anymore.

EXAMPLE
=======
::

    python scripts/run_gbm.py \\
      --input  datasets/gbm/transcripts.parquet \\
      --npmi   results/reference_npmi/gbm_npmi.csv \\
      --output results/tracer/gbm/transcripts_finetuned.parquet \\
      --platform xenium --seed 42 --max-runtime-sec 7200
"""

from __future__ import annotations

import argparse
import logging
import os
import signal
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd

# ── Path bootstrap ──────────────────────────────────────────────────────────
# parents[1] is the repo root (scripts/ -> TRACER/). The old script used
# parents[2] (= the directory *above* the repo), which inserted a
# non-existent ``<Desktop>/src`` onto sys.path and only worked by accident
# when tracer happened to be importable some other way.
_REPO_ROOT = Path(__file__).resolve().parents[1]
for _p in (str(_REPO_ROOT / "src"), str(_REPO_ROOT)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

REQUIRED_COLUMNS = {"x", "y", "feature_name", "cell_id"}
COMMON_COLUMN_ALIASES = {
    "x_location": "x",
    "y_location": "y",
    "z_location": "z",
}


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run TRACER on a GBM transcript parquet via the tested pipeline.",
    )
    parser.add_argument("--input", help="Transcript parquet path.")
    parser.add_argument("--npmi", help="PMI CSV generated by generate_pmi.py.")
    parser.add_argument("--output", help="Output parquet path for the finetuned transcript table.")
    parser.add_argument("--platform", default="xenium",
                        help="Platform preset (src/tracer/configs/platforms/<name>.toml).")
    parser.add_argument("--user-config", type=Path, default=None,
                        help="Optional user-override TOML on top of defaults+platform.")
    parser.add_argument("--pmi-threshold", type=float, default=None,
                        help="Override the in-pipeline PMI threshold (default: config).")
    parser.add_argument("--seed", type=int, default=42, help="Reproducibility seed.")
    parser.add_argument("--max-runtime-sec", type=float, default=None,
                        help="Abort with a clear error if the pipeline exceeds this "
                             "wall-clock budget (guards against silent hangs). "
                             "Default: no limit.")
    parser.add_argument(
        "--run-smoke-test",
        action="store_true",
        help="Run the built-in reproducibility smoke test and exit.",
    )
    return parser.parse_args()


def _validate_args(args: argparse.Namespace) -> None:
    if args.run_smoke_test:
        return
    missing = [flag for flag in ("input", "npmi", "output") if getattr(args, flag) is None]
    if missing:
        raise SystemExit(f"Missing required arguments: {', '.join('--' + name for name in missing)}")


def _setup_logging() -> logging.Logger:
    log = logging.getLogger("run_gbm")
    if log.handlers:
        return log
    log.setLevel(logging.INFO)
    log.propagate = False
    h = logging.StreamHandler(sys.stdout)
    h.setFormatter(logging.Formatter(
        fmt="%(asctime)s %(levelname)-7s %(message)s", datefmt="%H:%M:%S"))
    log.addHandler(h)
    return log


# ── Input loading (GBM-specific normalization, then standard expansion) ──────

def _load_transcripts(path: Path, log: logging.Logger) -> pd.DataFrame:
    df = pd.read_parquet(path)
    rename_map = {
        src: dst
        for src, dst in COMMON_COLUMN_ALIASES.items()
        if src in df.columns and dst not in df.columns
    }
    if rename_map:
        df = df.rename(columns=rename_map)
        log.info("Normalized columns: %s", rename_map)

    missing = sorted(REQUIRED_COLUMNS - set(df.columns))
    if missing:
        raise SystemExit(
            f"Transcripts parquet missing required columns {missing}. "
            "Accepted coordinate names are either x/y/z or raw Xenium "
            "x_location/y_location/z_location. "
            f"Present columns: {sorted(df.columns)}"
        )

    df = df.copy()
    # Match run_tracer.py's contract: ensure the optional columns the
    # pipeline branches on always exist, with the same dtypes.
    if "z" not in df.columns:
        df["z"] = np.float32(0.0)
    if "overlaps_nucleus" not in df.columns:
        df["overlaps_nucleus"] = np.uint8(0)
    if "transcript_id" not in df.columns:
        df["transcript_id"] = np.arange(len(df), dtype=np.int64)

    df["feature_name"] = df["feature_name"].astype(str).str.strip()
    df["cell_id"] = df["cell_id"].astype(str)
    for c in ("x", "y", "z"):
        df[c] = df[c].astype(np.float32)
    df["overlaps_nucleus"] = df["overlaps_nucleus"].astype(np.uint8)

    n_assigned = int((df["cell_id"] != "-1").sum())
    log.info("Loaded transcripts: %d rows, %d genes, assigned=%d, unassigned=%d, "
             "nuclear-seed=%s",
             len(df), df["feature_name"].nunique(), n_assigned,
             len(df) - n_assigned, bool(df["overlaps_nucleus"].any()))
    return df


def _load_npmi_panel(path: Path, log: logging.Logger) -> pd.DataFrame:
    """Load + symmetric-expand the NPMI panel exactly like run_tracer.py.

    The pipeline's W-matrix build expects long-format with BOTH directions
    per pair; the old run_gbm.py passed the raw single-direction CSV
    straight through, which half-fills W and corrupts PMI lookups.
    """
    df = pd.read_csv(path)
    if not {"gene_i", "gene_j"}.issubset(df.columns):
        raise SystemExit(
            f"NPMI panel missing gene_i/gene_j; columns: {list(df.columns)}"
        )
    if df.duplicated(["gene_i", "gene_j"]).any():
        log.warning("NPMI panel has duplicate pairs — keeping first occurrence.")
        df = df.drop_duplicates(["gene_i", "gene_j"], keep="first")
    rev = df.copy()
    rev["gene_i"], rev["gene_j"] = df["gene_j"].values, df["gene_i"].values
    panel = pd.concat([df, rev], ignore_index=True)
    panel = panel.loc[panel["gene_i"] != panel["gene_j"]].reset_index(drop=True)
    log.info("NPMI panel: %d rows after symmetric expansion (PMI=%s, NPMI=%s)",
             len(panel),
             "yes" if "PMI" in panel.columns else "no",
             "yes" if "NPMI" in panel.columns else "no")
    return panel


# ── Guardrail: max-runtime watchdog ─────────────────────────────────────────

class _RuntimeExceeded(RuntimeError):
    pass


def _install_watchdog(max_runtime_sec: float | None, log: logging.Logger):
    """Arm a SIGALRM watchdog that aborts with a clear message instead of
    hanging silently. Returns a cleanup callable (disarm)."""
    if not max_runtime_sec or max_runtime_sec <= 0:
        return lambda: None
    if not hasattr(signal, "SIGALRM"):  # non-unix fallback
        log.warning("SIGALRM unavailable on this platform; --max-runtime-sec ignored.")
        return lambda: None

    def _handler(signum, frame):
        raise _RuntimeExceeded(
            f"TRACER pipeline exceeded the --max-runtime-sec budget "
            f"({max_runtime_sec:.0f}s) and was aborted. This usually means an "
            f"oversized input (run on an ROI/sample, not whole tissue) or a "
            f"degenerate stage. Re-run with TRACER_STAGE_VERBOSE=1 to see which "
            f"stage stalled."
        )

    signal.signal(signal.SIGALRM, _handler)
    signal.setitimer(signal.ITIMER_REAL, float(max_runtime_sec))
    log.info("Watchdog armed: max runtime %.0fs", max_runtime_sec)
    return lambda: signal.setitimer(signal.ITIMER_REAL, 0.0)


def main() -> None:
    args = _parse_args()
    _validate_args(args)
    log = _setup_logging()

    from tracer.core import reproducibility_smoke_test, set_reproducibility_seed

    if args.run_smoke_test:
        set_reproducibility_seed(args.seed)
        reproducibility_smoke_test(seed=args.seed)
        log.info("Smoke test passed")
        return

    input_path = Path(args.input)
    npmi_path = Path(args.npmi)
    output_path = Path(args.output)

    # Progress logging from the pipeline's per-stage accounting.
    os.environ.setdefault("TRACER_STAGE_VERBOSE", "1")
    np.random.seed(args.seed)
    os.environ["PYTHONHASHSEED"] = str(args.seed)
    set_reproducibility_seed(args.seed)

    df = _load_transcripts(input_path, log)
    panel = _load_npmi_panel(npmi_path, log)

    from tracer.config import load_config
    import tracer.pipeline as pipeline

    cfg = load_config(path=args.user_config, platform=args.platform)
    if args.pmi_threshold is not None:
        pipeline.PMI_THR = float(args.pmi_threshold)
        log.info("PMI threshold override: pipeline.PMI_THR = %.4f", pipeline.PMI_THR)

    log.info("Calling run_segmented_pipeline (df=%d rows, panel=%d pairs, platform=%s)",
             len(df), len(panel), args.platform)
    disarm = _install_watchdog(args.max_runtime_sec, log)
    t0 = time.perf_counter()
    try:
        df_out, progression = pipeline.run_segmented_pipeline(
            df=df, npmi_panel=panel, cfg=cfg,
        )
    except _RuntimeExceeded as exc:
        log.error("%s", exc)
        raise SystemExit(2)
    finally:
        disarm()
    wall = time.perf_counter() - t0

    # Per-stage progress summary (clear, non-silent).
    for s in progression:
        log.info("[stage] %-22s cells=%-7s partials=%-7s components=%-7s unassigned=%-9s %.2fs",
                 s.get("stage", ""), f"{s.get('n_cells', 0):,}",
                 f"{s.get('n_partials', 0):,}", f"{s.get('n_components', 0):,}",
                 f"{s.get('n_unassigned_tx', 0):,}", (s.get("stage_seconds") or 0.0))
    log.info("TRACER done — %d stages, output rows=%d, wall=%.1fs",
             len(progression), len(df_out), wall)

    # Output contract: rename the pipeline's `stitched` label column to
    # `cell_id_finetuned` for backward compatibility with GBM consumers.
    df_finetuned = df_out.rename(columns={"stitched": "cell_id_finetuned"})
    output_path.parent.mkdir(parents=True, exist_ok=True)
    df_finetuned.to_parquet(output_path, index=False)
    log.info("Saved finetuned output to: %s", output_path)


if __name__ == "__main__":
    main()
